# Generated by Django 3.2.5 on 2021-08-06 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nasledime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WillModel',
            new_name='Will',
        ),
    ]
