# Generated by Django 3.2.5 on 2021-08-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasledime', '0002_rename_willmodel_will'),
    ]

    operations = [
        migrations.RenameField(
            model_name='will',
            old_name='personal_identification_num',
            new_name='uic',
        ),
    ]
