# Generated by Django 3.2.5 on 2021-08-07 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nasledime', '0003_rename_personal_identification_num_will_uic'),
    ]

    operations = [
        migrations.AddField(
            model_name='will',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
