# Generated by Django 3.2.6 on 2021-08-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_nasledimeuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nasledimeuser',
            options={},
        ),
    ]
