# Generated by Django 3.2.6 on 2021-08-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_nasledimeuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nasledimeuser',
            options={'permissions': (('add_will', 'can_add_will'), ('change_will', 'can_change_will'), ('delete_will', 'can_delete_will'), ('view_will', 'can_view_will'))},
        ),
    ]
